services:
  - type: web
    name: api-backend
    env: python
    region: oregon  # vous pouvez choisir la région la plus proche (a rechercher)
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn xluss4D-backend.wsgi:application
    autoDeploy: true
    envVars:
      - key: SECRET_KEY
        fromSecret: secret-key
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromSecret: database-url